In [1]:
import torch

In [2]:
# Creating a 3x2 matrix (3 rows, 2 columns)
# This could represent 3 people with 2 features each
m = torch.tensor([
    [22.0, 60.0], # Person 1: 22 years, 60kg
    [25.0, 75.0], # Person 2: 25 years, 75kg
    [30.0, 80.0]  # Person 3: 30 years, 80kg
])

In [4]:
print(f"Matrix:\n{m}")

Matrix:
tensor([[22., 60.],
        [25., 75.],
        [30., 80.]])


In [5]:
print(f"Shape: {m.shape}") # Output: torch.Size([3, 2])

Shape: torch.Size([3, 2])


In [6]:
print(f"Rank (ndim): {m.ndim}") # Output: 2

Rank (ndim): 2


In [7]:
# Matrix A (3x2)
A = torch.tensor([
    [1, 2],
    [3, 4],
    [5, 6]
])

# Matrix B (2x1) - Let's call it a weight vector
B = torch.tensor([
    [10],
    [20]
])

In [8]:
# Matrix Multiplication using '@' symbol or torch.mm
result = A @ B

In [9]:
print(f"Result of A @ B:\n{result}")
# Calculation: 
# [1*10 + 2*20] = [50]
# [3*10 + 4*20] = [110]
# [5*10 + 6*20] = [170]

Result of A @ B:
tensor([[ 50],
        [110],
        [170]])


In [10]:
# Creating two matrices with the shapes you mentioned
# Matrix A: 100 samples, 50 features each
A = torch.randn(100, 50)

# Matrix B: 50 input features, 10 output features (Weight Matrix)
B = torch.randn(50, 10)

# Performing matrix multiplication
result = torch.mm(A, B) # Or: result = A @ B

In [11]:
print(f"Shape of A: {A.shape}")
print(f"Shape of B: {B.shape}")
print(f"Shape of Result: {result.shape}")

Shape of A: torch.Size([100, 50])
Shape of B: torch.Size([50, 10])
Shape of Result: torch.Size([100, 10])


In [12]:
# A matrix of shape [3, 4]
A = torch.randn(3, 4)

# Another matrix of shape [3, 4]
B = torch.randn(3, 4)

# This will throw an error:
# result = torch.mm(A, B) 

# This will work perfectly:
result = torch.mm(A, B.T) # B.T changes [3, 4] to [4, 3]

In [13]:
print(f"Original B shape: {B.shape}")
print(f"Transposed B shape: {B.T.shape}")
print(f"Result shape: {result.shape}") # Output: [3, 3]

Original B shape: torch.Size([3, 4])
Transposed B shape: torch.Size([4, 3])
Result shape: torch.Size([3, 3])


In [14]:
# Ek image tensor: [Channels, Height, Width]
img = torch.randn(3, 28, 28) 

# Permute ka istemal:
# Hum keh rahe hain: 
# Jo 1st index (Height) hai use 0 pe le aao
# Jo 2nd index (Width) hai use 1 pe le aao
# Jo 0th index (Channels) hai use 2 pe le jao
img_permuted = img.permute(1, 2, 0)

In [15]:
print(f"Original shape: {img.shape}")          # [3, 28, 28]
print(f"Permuted shape: {img_permuted.shape}") # [28, 28, 3]

Original shape: torch.Size([3, 28, 28])
Permuted shape: torch.Size([28, 28, 3])


In [16]:
# एक 2x2 Matrix बनाते हैं
A = torch.tensor([[1.0, 2.0], 
                  [3.0, 4.0]])

# Inverse निकालना (sirf square matrix ka hi inverse niklta hai)
A_inv = torch.linalg.inv(A)

In [17]:
print("Original Matrix A:")
print(A)

print("\nInverse Matrix (A_inv):")
print(A_inv)

Original Matrix A:
tensor([[1., 2.],
        [3., 4.]])

Inverse Matrix (A_inv):
tensor([[-2.0000,  1.0000],
        [ 1.5000, -0.5000]])


In [18]:
# Proof: A * A_inv = Identity Matrix (I)
# Identity matrix में diagonal पर 1 और बाकी 0 होता है
identity = torch.mm(A, A_inv)
print("\nA * A_inv (Identity Matrix):")
print(torch.round(identity)) # round ताकि 0.00000 zero दिखे


A * A_inv (Identity Matrix):
tensor([[1., 0.],
        [0., 1.]])


In [19]:
# 1. Well-conditioned Matrix (Strong and Stable)
stable_matrix = torch.tensor([[1.0, 0.0], 
                             [0.0, 1.0]])

cond_stable = torch.linalg.cond(stable_matrix)
print(f"Stable Matrix Condition Number: {cond_stable.item()}") 
# Output: 1.0 (Best possible)

Stable Matrix Condition Number: 1.0


In [20]:
# 2. Ill-conditioned Matrix (Weak and Sensitive)
# यहाँ दोनों rows लगभग एक जैसी हैं (0.0001 का फर्क है) ya lagbhag ek durse ke kuch times hai jese 2 aur 4.001
weak_matrix = torch.tensor([[1.0, 1.0], 
                            [1.0, 1.0001]])

cond_weak = torch.linalg.cond(weak_matrix)
print(f"Weak Matrix Condition Number: {cond_weak.item()}") 
# Output: Bahut bada number aayega (Jaise 40000+)

Weak Matrix Condition Number: 39949.3671875


In [21]:
# Case A: Ideal Matrix (Well-conditioned)
# Isme rows ek dusre se bilkul alag hain
A_ideal = torch.tensor([[1.0, 0.0], 
                        [0.0, 1.0]])

# Case B: Ill-conditioned Matrix (Jo aapne pucha)
# Isme 2nd row lagbhag 1st row ki double hai (sirf 0.0001 ka farak)
A_ill = torch.tensor([[1.0, 2.0], 
                      [2.0, 4.0001]])

# Ab hum dono ka Inverse nikalte hain
inv_ideal = torch.linalg.inv(A_ideal)
inv_ill = torch.linalg.inv(A_ill)

print("Inverse of Ideal Matrix:\n", inv_ideal)
# Iska result chota aur stable aayega

print("\nInverse of Ill-conditioned Matrix:\n", inv_ill)
# Iska result bada aur unstable aayega

Inverse of Ideal Matrix:
 tensor([[1., 0.],
        [0., 1.]])

Inverse of Ill-conditioned Matrix:
 tensor([[ 39946.7539, -19972.8770],
        [-19972.8770,   9986.4385]])


In [23]:
# Ek chota sa noise vector
noise = torch.tensor([0.0001, 0.0001])

# Result par asar: Inverse @ Noise
result_ideal = inv_ideal @ noise
result_ill = inv_ill @ noise

print("\nEffect of Noise on Ideal Matrix:", result_ideal)
print("Effect of Noise on Ill-conditioned Matrix:", result_ill)


Effect of Noise on Ideal Matrix: tensor([1.0000e-04, 1.0000e-04])
Effect of Noise on Ill-conditioned Matrix: tensor([ 1.9974, -0.9986])
