In [1]:
import torch

In [2]:
# 1. MANUAL DATA POINTS
# Creating a simple curve (y = x^2) with manual points
x = torch.tensor([-2.0, -1.0, 0.0, 1.0, 2.0])
y = torch.tensor([4.2, 0.8, 0.1, 1.2, 3.9]) # Added slight noise manually

In [3]:
# 2. HIGH BIAS (UNDERFITTING)
# A very simple model (straight line) that ignores the curve
# Logic: y = 0.5 * x + 2.0 (Straight line)
y_high_bias = 0.5 * x + 2.0

In [4]:
# 3. HIGH VARIANCE (OVERFITTING)
# A very complex model that tries to touch every single noise point
# Logic: Squiggly line that passes through all points but is erratic
y_high_variance = torch.tensor([4.2, 0.8, 0.1, 1.2, 3.9]) 

In [5]:
# 4. PERFECT FIT (GENERALIZED)
# A balanced model that understands the rule (y = x^2)
y_balanced = x**2

In [6]:
print(y_high_bias)
print(y_high_variance)
print(y_balanced)

tensor([1.0000, 1.5000, 2.0000, 2.5000, 3.0000])
tensor([4.2000, 0.8000, 0.1000, 1.2000, 3.9000])
tensor([4., 1., 0., 1., 4.])
